[[redirects]]
from = "/favicon/*"
to = "https://res.cloudinary.com/withbrio/image/fetch/f_auto/t_favicon/https://withbr.io/:splat"
status = 200

[[redirects]]
from = "/covers/*"
to = "https://res.cloudinary.com/withbrio/image/fetch/f_auto/t_covers/https://withbr.io/:splat"
status = 200

[[redirects]]
from = "/products/*"
to = "https://res.cloudinary.com/withbrio/image/fetch/f_auto/t_products/https://withbr.io/:splat"
status = 200
