[[redirects]]
from = "/favicon/:image"
to = "https://res.cloudinary.com/withbrio/image/fetch/f_auto/q_80/t_favicon/https://withbr.io/images/:image"
status = 200

[[redirects]]
from = "/products/:image"
to = "https://res.cloudinary.com/withbrio/image/fetch/f_auto/q_80/t_products/https://withbr.io/images/:image"
status = 200

[[redirects]]
from = "/covers/:image"
to = "https://res.cloudinary.com/withbrio/image/fetch/f_auto/q_80/t_covers/https://withbr.io/images/:image"
status = 200
