---
backend:
  name: git-gateway
  branch: main

logo_url: https://res.cloudinary.com/car-talk-vehicle-donation-program/image/upload/v1674870469/ct-logo.svg
show_preview_links: false

media_folder: "src/images/" # Media files will be stored in the repo under static/images/
public_folder: "/images/" # The src attribute for uploaded media will begin with /images/

collections:
  - name: retailers
    label: Retailers
    label_singular: Retailer
    folder: src/content/retailers/
    slug: "{{slug}}"
    extension: md
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items in this collection
    identifier_field: name
    summary: "{{fields.name}}"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - label: "Name"
        name: "name"
        widget: "string"
      - label: Brick and Mortar Stores
        label_singular: Store
        name: physical_locations
        widget: list
        collapsed: true
        minimize_collapsed: false
        allow_add: true
        summary: "{{fields.city}}, {{fields.state}}"
        fields:
          - label: Branch Name
            name: branch_name
            widget: string
            hint: If the retailer has multiple locations, what branch is this (e.g., for REI, it would be 'North Conway' or 'Bedford'). Leave blank if there's only one store
          - label: Street 1
            name: street1
            widget: string
            required: true
          - label: Street 2
            name: street2
            widget: string
            required: false
          - label: City
            name: city
            widget: string
            required: true
          - label: State
            name: state
            widget: string
            required: true
          - label: Zip Code
            name: postal_code
            widget: string
            required: true
          - label: Phone
            name: phone
            widget: string
            required: false
          - label: Email
            name: email
            widget: string
            required: false
          - label: Store URL
            name: store_url
            widget: string
            required: false
          - label: Products Carried
            name: products
            widget: relation
            collection: products
            search_fields: ["title"]
            value_field: "title"
            display_fields: ["title"]
            multiple: true
            required: true
            min: 1

  - name: products
    label: Products
    label_singular: Product
    folder: src/content/products/
    slug: "{{sku}}"
    extension: md
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items in this collection
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "SKU"
        name: "sku"
        widget: "string"

      # - label: List of Cities
      #   name: list_of_cities
      #   widget: array
      #   allow_add: true
